### ISSUE TITLE
增加跨域

### ISSUE THREAD

**Issue by xsthunder** [peakchen90/mock-dev-server#2]
你好，这个工具非常方便，我很喜欢路径即路由这样简洁的设计，你的想法很棒！

我在使用过程中遇到跨域的问题，希望能够增加一个允许跨域的feature，实现代码如下。

```js
/src/server.js
class Server {
  constructor(port) {
    this.app = app
                /* 允许跨域 */
                this.app.use( "*",(req, res, next) =>{
                    res.header("Access-Control-Allow-Origin", "*");
                    next();
                });
    this.port = port
    this.router = new Router()
    // 请求日志
    this.app.use(morgan('dev'))
    // 保存监听更新开始时间
    this.updateStart = Date.now()
  }
```

前端项目
mock server 挂载在localhost:3333
前端配置 请求api url 走 localhost:3333
前端spa挂载在 localhost:8080
这样的情况下就会出现跨域的问题

虽然也可以走devServer proxy转发请求到mock server，绕过跨域，但我的项目是完全的前后端分离，同时也不想在webpack.devServer加proxy。另外考虑在preproduction环境下使用 mock server，不希望自己实现proxy来绕过跨域。

我认为本地的mock服务器限制可以更加宽松。额外加入配置项也是可以考虑的。

我这里也可以发pr。

希望你能考虑一下。

**Comment by peakchen90** [comment]
@xsthunder 这段时间太忙了，都没时间看github。我觉得这个想法是可以的，欢迎来PR
